# Generated by Django 4.2.8 on 2023-12-14 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Indoor', 'I'), ('Outdoor', 'O')], max_length=255, null=True),
        ),
    ]
