# Generated by Django 4.2.8 on 2023-12-14 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='date_crreated',
        ),
        migrations.AddField(
            model_name='order',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
